# Welcome to Jekyll!
# push "bundle exec jekyll serve" to start this...

title: "#BYDINOKI.com"
locale: es_MX
email: contact@bydinoki.com
description: >- # this means to ignore newlines until "baseurl:"
 #BYDINOKI es una página básica que ofrece todas las Noticias
 y Novedades para Dinoki ON y toda su trayectoria en un Sitio Web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bydinoki.onrender.com" # the base hostname & protocol for your site, e.g. http://example.com
iglink: "https://instagram.com/dinoki_0n"
ytlink:  "https://youtube.com/channel/UCmf1ZezKYhGjPGR1eZUuDlw"
cseos: ""


# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
